import {
  AirQualityData,
  PlayerStats,
  Badge,
  Mission,
  CommunityPost,
  EventItem,
  Contribution,
  RewardItem,
  CompanyInfo,
  CSRProject,
  EnvironmentalReport,
  AIRecommendation,
  ZoneDetail,
  Complaint,
} from '@/types';

export const mockAirQuality: AirQualityData = {
  aqi: 72,
  level: 'MODERATE',
  zone: 'Delhi NCR - Zone 04 (Central Eco Belt)',
  city: 'New Delhi',
  updatedAt: '2 mins ago',
  isLive: true,
  pm25: 32,
  pm10: 58,
  no2: 24.5,
  so2: 12.1,
  co: 0.8,
  o3: 42.0,
  temperature: 31,
  humidity: 58,
  windSpeed: 12,
  windDirection: 'NW',
};

export const mockPlayerStats: PlayerStats = {
  id: 'usr_001',
  name: 'Aarav Sharma',
  username: 'aarav_eco',
  avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
  level: 12,
  currentXp: 1240,
  nextLevelXp: 1700,
  rank: 'Air Guardian',
  globalRank: 18,
  streakDays: 8,
  contributionScore: 342,
  co2OffsetKg: 84.5,
  treesPlanted: 14,
  reportsSubmitted: 9,
  missionsCompleted: 26,
  availablePoints: 2450,
  badgesCount: 9,
};

export const mockBadges: Badge[] = [
  {
    id: 'badge_1',
    title: 'Air Guardian',
    description: 'Maintained 7+ consecutive clean air mission days in hotspot zones.',
    icon: 'Wind',
    category: 'AIR',
    unlockedAt: '2026-08-20',
    accentColor: 'blue',
  },
  {
    id: 'badge_2',
    title: 'Tree Warrior',
    description: 'Planted and verified 10 native oxygen-generating trees.',
    icon: 'Trees',
    category: 'IMPACT',
    unlockedAt: '2026-08-28',
    accentColor: 'green',
  },
  {
    id: 'badge_3',
    title: 'Smog Hunter',
    description: 'Submitted 5 verified industrial/burning pollution alerts.',
    icon: 'Flame',
    category: 'COMMUNITY',
    unlockedAt: '2026-09-02',
    accentColor: 'red',
  },
  {
    id: 'badge_4',
    title: '8-Day Streak Master',
    description: 'Logged daily actions and monitored neighborhood AQI for 8 days straight.',
    icon: 'Zap',
    category: 'STREAK',
    unlockedAt: '2026-09-05',
    accentColor: 'yellow',
  },
  {
    id: 'badge_5',
    title: 'Climate Defender',
    description: 'Contribute over 100kg CO₂ reduction through verified missions.',
    icon: 'ShieldCheck',
    category: 'IMPACT',
    progress: 84.5,
    maxProgress: 100,
    accentColor: 'blue',
  },
  {
    id: 'badge_6',
    title: 'Community Mentor',
    description: 'Inspire 20 fellow citizens to complete local air cleaning quests.',
    icon: 'Users',
    category: 'COMMUNITY',
    progress: 14,
    maxProgress: 20,
    accentColor: 'green',
  },
];

export const mockMissions: Mission[] = [
  {
    id: 'm_104',
    code: 'MISSION #104',
    title: 'Plant 5 Native Neem or Peepal Trees',
    description: 'Plant native high-canopy trees in identified Zone 04 green pockets to naturally scrub particulate matter.',
    category: 'Tree Plantation',
    difficulty: 'MEDIUM',
    xpReward: 250,
    impactScore: 40,
    estimatedMinutes: 45,
    locationZone: 'Zone 04 - Dwarka Greens',
    status: 'AVAILABLE',
    participantsCount: 84,
    deadlineHours: 18,
    instructions: [
      'Locate designated community plantation spot in Zone 04',
      'Plant native saplings at minimum 2-meter spacing',
      'Water thoroughly and capture geo-tagged before/after photo',
      'Submit verification photo in the app to claim rewards',
    ],
  },
  {
    id: 'm_105',
    code: 'MISSION #105',
    title: 'Report Illegal Open Biomass Burning',
    description: 'Spot and report roadside leaf or waste combustion before it creates severe localized micro-smog.',
    category: 'Community Reporting',
    difficulty: 'EASY',
    xpReward: 120,
    impactScore: 35,
    estimatedMinutes: 10,
    locationZone: 'Zone 02 - Okhla Industrial Belt',
    status: 'AVAILABLE',
    participantsCount: 142,
    deadlineHours: 6,
    instructions: [
      'Maintain safe distance from combustion site',
      'Take a clear photo showing smoke origin',
      'Confirm automatic GPS location tag',
      'Select severity and submit for municipal taskforce intervention',
    ],
  },
  {
    id: 'm_106',
    code: 'MISSION #106',
    title: 'HVAC & Air Filter Check in Community Center',
    description: 'Inspect and clean air intake mesh filters to reduce indoor PM2.5 buildup during peak pollution hours.',
    category: 'Air Cleaning',
    difficulty: 'MEDIUM',
    xpReward: 180,
    impactScore: 30,
    estimatedMinutes: 30,
    locationZone: 'Zone 01 - Connaught Hub',
    status: 'AVAILABLE',
    participantsCount: 39,
    deadlineHours: 24,
    instructions: [
      'Check pre-filters for heavy dust accumulation',
      'Clean or replace HEPA filter cartridges according to guidelines',
      'Log particle count before and after servicing',
    ],
  },
  {
    id: 'm_107',
    code: 'MISSION #107',
    title: 'Low-Emission Carpool & Transit Rally',
    description: 'Log 3 days of public metro or shared EV transit instead of solo petrol vehicle commuting.',
    category: 'Climate Resilience',
    difficulty: 'HARD',
    xpReward: 350,
    impactScore: 60,
    estimatedMinutes: 120,
    locationZone: 'Citywide Corridor',
    status: 'AVAILABLE',
    participantsCount: 312,
    deadlineHours: 72,
    instructions: [
      'Use metro, electric bus, or shared electric cab',
      'Upload transit ticket or QR trip confirmation',
      'Achieve 15kg cumulative CO₂ reduction',
    ],
  },
];

export const mockCommunityPosts: CommunityPost[] = [];

export const mockEvents: EventItem[] = [
  {
    id: 'evt_01',
    title: 'Clean Air Mega Marathon & Community Quest',
    tagline: 'Run for Blue Skies & Deploy 100 Native Saplings',
    description: 'Join over 300 urban environmentalists, students, and corporate CSR teams in a mass tree plantation and air quality awareness drive.',
    date: 'Saturday, Sep 12, 2026',
    time: '06:30 AM - 10:00 AM IST',
    location: 'Lodhi Garden Central Amphitheatre',
    city: 'New Delhi',
    zone: 'Zone 01',
    participantsCount: 284,
    maxParticipants: 400,
    impactLevel: 'Very High',
    xpReward: 500,
    organizer: 'Delhi Clean Air Collective & AirGuard',
    isJoined: true,
    category: 'Community Gathering',
  },
  {
    id: 'evt_02',
    title: 'Urban Micro-Forest Hackathon',
    tagline: 'Miyawaki Dense Forest Creation in 48 Hours',
    description: 'Transform an abandoned concrete plot into a high-density biodiverse urban lung with fast-growing indigenous species.',
    date: 'Sunday, Sep 20, 2026',
    time: '08:00 AM - 04:00 PM IST',
    location: 'Sector 62 Eco Park',
    city: 'Noida',
    zone: 'Zone 05',
    participantsCount: 118,
    maxParticipants: 150,
    impactLevel: 'High',
    xpReward: 400,
    organizer: 'Green Earth Initiative',
    isJoined: false,
    category: 'Reforestation',
  },
];

export const mockContributions: Contribution[] = [
  {
    id: 'c_01',
    title: 'Planted 3 Native Ashoka Trees',
    type: 'Tree Plantation',
    category: 'Reforestation',
    date: 'Sep 06, 2026',
    xp: 200,
    impactScore: 40,
    co2Saved: 18.2,
    status: 'Verified',
    location: 'Dwarka Sector 14 Park',
  },
  {
    id: 'c_02',
    title: 'Reported Construction Dust Spillage',
    type: 'Pollution Reporting',
    category: 'Enforcement',
    date: 'Sep 05, 2026',
    xp: 100,
    impactScore: 25,
    co2Saved: 8.5,
    status: 'Verified',
    location: 'Outer Ring Road Flyover',
  },
  {
    id: 'c_03',
    title: 'Organized Apartment Composting Drive',
    type: 'Waste Management',
    category: 'Community',
    date: 'Sep 04, 2026',
    xp: 150,
    impactScore: 30,
    co2Saved: 14.0,
    status: 'Verified',
    location: 'Heritage Apartments Complex',
  },
];

export const mockRewards: RewardItem[] = [
  {
    id: 'rew_1',
    title: '₹250 Eco Store Coupon',
    provider: 'GreenLife Essentials',
    category: 'Eco Store',
    pointsCost: 1000,
    discountValue: '₹250 OFF',
    description: 'Valid on zero-waste personal care, bamboo products, and air purifying plants.',
    expiryDays: 30,
    image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=300&auto=format&fit=crop&q=80',
    accent: 'green',
  },
  {
    id: 'rew_2',
    title: 'Plant 1 Geotagged Tree in Your Name',
    provider: 'Sankalp Taru Foundation',
    category: 'Green Action',
    pointsCost: 500,
    discountValue: '1 Native Tree',
    description: 'Real verified tree planted in arid community belt with lifetime satellite monitoring link.',
    expiryDays: 90,
    image: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=300&auto=format&fit=crop&q=80',
    accent: 'blue',
  },
  {
    id: 'rew_3',
    title: 'Public Metro / EV Transit Pass',
    provider: 'Urban Mobility Transit',
    category: 'Transport',
    pointsCost: 800,
    discountValue: '5 Free Rides',
    description: 'Zero emission commute credit redeemable on all city smart transit gateways.',
    expiryDays: 15,
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=300&auto=format&fit=crop&q=80',
    accent: 'yellow',
  },
  {
    id: 'rew_4',
    title: 'HEPA Air Purifier Filter Replacement',
    provider: 'AeroShield Tech',
    category: 'Coupon',
    pointsCost: 1800,
    discountValue: '35% OFF',
    description: 'High efficiency True HEPA + activated carbon replacement filter pack.',
    expiryDays: 60,
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=300&auto=format&fit=crop&q=80',
    accent: 'red',
  },
];

export const mockLeaderboard = [
  { rank: 1, name: 'Vikramaditya Das', username: 'vikram_cleanair', level: 24, xp: 9450, impact: 820, avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80', badge: '🏆 Climate Champion' },
  { rank: 2, name: 'Sunita Reddy', username: 'sunita_green', level: 22, xp: 8890, impact: 790, avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80', badge: '🌳 Forest Guardian' },
  { rank: 3, name: 'Ananya Deshmukh', username: 'ananya_eco', level: 19, xp: 7620, impact: 680, avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80', badge: '🌬️ Air Sentinel' },
  { rank: 4, name: 'Kabir Mehta', username: 'kabir_pure', level: 17, xp: 6410, impact: 590, avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80', badge: '🌱 Eco Pioneer' },
  { rank: 18, name: 'Aarav Sharma (You)', username: 'aarav_eco', level: 12, xp: 1240, impact: 342, avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80', isCurrent: true, badge: '🛡️ Air Guardian' },
];

export const mockCompany: CompanyInfo = {
  id: 'comp_01',
  name: 'Tata Consultancy ESG & Tech',
  logo: '🏢',
  industry: 'Technology & Enterprise Solutions',
  location: 'New Delhi & Mumbai HQ',
  csrRank: 3,
  totalCsrFunding: '₹42,50,000',
  employeesCount: 1420,
  impactScore: 88400,
  organizationsSupported: 12,
  activeProjects: 6,
};

export const mockCsrProjects: CSRProject[] = [
  {
    id: 'csr_p1',
    title: 'Urban Smog Purification & Bio-Filter Towers',
    organization: 'Clean Air Foundation India',
    orgLogo: '🌱',
    category: 'Air Cleaning Tech',
    requiredFunds: 500000,
    fundedAmount: 380000,
    targetImpact: 'Purify 80M cubic meters of ambient air near traffic junctions',
    location: 'Delhi NCR (5 Key Nodes)',
    treesTarget: 4000,
    householdsTarget: 2400,
    status: 'ACTIVE',
  },
  {
    id: 'csr_p2',
    title: 'School Rooftop Solar & Clean Air Sanctuaries',
    organization: 'Prana Climate Alliance',
    orgLogo: '☀️',
    category: 'Vulnerable Communities',
    requiredFunds: 750000,
    fundedAmount: 750000,
    targetImpact: 'Provide 18 public schools with clean air filters & solar roofs',
    location: 'East Delhi & Ghaziabad',
    treesTarget: 1200,
    householdsTarget: 5600,
    status: 'FULLY_FUNDED',
  },
  {
    id: 'csr_p3',
    title: 'Stubble-to-Biochar Farmer Incentive Program',
    organization: 'AgriResilience Network',
    orgLogo: '🌾',
    category: 'Biomass Management',
    requiredFunds: 1200000,
    fundedAmount: 840000,
    targetImpact: 'Eliminate open field burning over 1,500 agricultural acres',
    location: 'Punjab - Haryana Agro Belt',
    treesTarget: 8500,
    householdsTarget: 12000,
    status: 'ACTIVE',
  },
];

export const mockReports: EnvironmentalReport[] = [];

export const mockAIRecommendations: AIRecommendation[] = [
  {
    id: 'ai_rec_01',
    title: 'Micro-Hotspot Detected: Zone 04 Particulate Surge',
    zone: 'Delhi NCR - Zone 04',
    issue: 'Particulate matter (PM2.5) increased by 38% over 3 hours due to wind inversion and local traffic idling.',
    triggerEvent: 'Automated IoT Sensor Convergence + 4 Resident Reports',
    recommendedAction: 'Deploy 2 Mobile Water Misting Cannons & Trigger "Anti-Idling Public Awareness" Community Mission for 150 local players.',
    expectedImpact: 'Estimated 22-28% PM2.5 reduction within 4 hours; high community mobilization.',
    confidenceScore: 87,
    supportingData: [
      'IoT Sensor Node #408: PM2.5 jumped from 48 to 118 μg/m³',
      'Wind Speed dropped below 3 km/h (stagnant boundary layer)',
      '142 active players available within 2km radius',
    ],
    status: 'PENDING_APPROVAL',
    generatedAt: '12 mins ago',
  },
  {
    id: 'ai_rec_02',
    title: 'Opportunity: Corporate CSR Funding for Urban Lung Corridor',
    zone: 'Zone 02 - Okhla & Sarita Vihar',
    issue: 'Open barren railway parcel causing seasonal dust storms during dry spells.',
    triggerEvent: 'Satellite NDVI vegetation drop below 0.15 threshold',
    recommendedAction: 'Match with Tata ESG fund to create a 3-hectare Miyawaki bio-shield.',
    expectedImpact: 'High: Long-term filtration of ~14 tons of PM particles annually.',
    confidenceScore: 92,
    supportingData: [
      'Land verification completed by municipal authorities',
      'Matching funds of ₹8.4L already pre-committed by 2 corporations',
      'Projected CO₂ sequestration: 35 tonnes/year',
    ],
    status: 'PENDING_APPROVAL',
    generatedAt: '1 hour ago',
  },
];

export const mockZones: ZoneDetail[] = [
  { id: 'z1', name: 'Zone 01 - Connaught & Central Vista', city: 'New Delhi', aqi: 62, temperature: 30, humidity: 55, wind: '14 km/h NW', pollutionLevel: 'Moderate', activeReports: 2, activeMissions: 8, population: '420,000', status: 'Optimal' },
  { id: 'z2', name: 'Zone 02 - Okhla & South Industrial', city: 'New Delhi', aqi: 168, temperature: 33, humidity: 48, wind: '5 km/h W', pollutionLevel: 'Unhealthy', activeReports: 14, activeMissions: 16, population: '890,000', status: 'Critical' },
  { id: 'z3', name: 'Zone 03 - Rohini & North Residential', city: 'New Delhi', aqi: 115, temperature: 31, humidity: 52, wind: '9 km/h N', pollutionLevel: 'Poor', activeReports: 6, activeMissions: 11, population: '1,120,000', status: 'Warning' },
  { id: 'z4', name: 'Zone 04 - Dwarka Greens & Airport Belt', city: 'New Delhi', aqi: 72, temperature: 31, humidity: 58, wind: '12 km/h NW', pollutionLevel: 'Moderate', activeReports: 3, activeMissions: 14, population: '650,000', status: 'Optimal' },
  { id: 'z5', name: 'Zone 05 - Noida Tech Corridor', city: 'Noida', aqi: 142, temperature: 32, humidity: 50, wind: '7 km/h E', pollutionLevel: 'Poor', activeReports: 8, activeMissions: 9, population: '780,000', status: 'Warning' },
];

export const mockComplaints: Complaint[] = [];

